### PR TITLE
Multiblock machine tweaks

### PR DESCRIPTION
**Pull request by kirderf1**
Has some cleanup, refactors and javadoc for the multiblock class.
Introduces a new approach to removing entire multiblock machines that should work well even if the machine is already partially broken. Unlike its predecessor, this approach is not recursive.
The function for destroying an entire machine has been moved from `MultiMachineBlock` to a new interface `EditmodeDestroyable`. This interface has been implemented for all blocks extending `MultiMachineBlock` with the exception of `LotusTimeCapsuleMultiblock`, which will no longer inherit this behavior.

I also considered removing `MultiMachineBlock` entierly, but noticed that it was being used in `EditToolDrag.isMultiblock()`. I might end up suggesting a different approach in the PR review, but I'll first need to go through `EditToolDrag` and see what's going on there.

### CODE REVIEW

**Comment by kirderf1** [comment]
Ah right, I need to check it out with cruxite dowels in cruxtruders and totem lathes as well.

**Comment by seriousCoolness** [comment]
It works really well aside from, as you mentioned the cruxtruder and totem lathe cruxite dowel-blocks. But other than those, this implementation is REALLY clean! Thanks so much for doing this-- I just couldn't figure it out for the life of me! As soon as you account for the dowel-blocks, I'll merge it.

**Comment by kirderf1** [comment]
After looking at it, I'd say that the cruxtruder dowel should be removed in general (if the pipe below it is broken), and is thus a general problem that I'll solve directly on the main branch. However the totem lathe dowel I want removed specifically when the entire machine is broken in one, so I'll have that fixed in this PR.

But yeah! The functionality of the multiblock class had to mature a bit, such as with the Placement record and other utilities, but with these things in place, it's really clean!

**Comment by kirderf1** [comment]
That has been done now. Also noticed that the dowel item wasn't being dropped from the totem lathe dowel, but that's also a general problem that I'd rather fix outside the PR.

The registration functions for placement entries start to become a little bit unwieldy, so it might become relevant to use a builder pattern instead. But that's for some other time.

**Pull request merged**
